import { ArrowLeft, LoaderCircle, Mic, Square } from 'lucide-react';
import FoxMascot from '../parts/FoxMascot';
import Dartboard from '../parts/Dartboard';
import type { TeachPhase, } from '@/hooks/useTeachSession';
import type { TeachTopic } from '@/lib/games/teach/types';

export default function ExplainScreen({ topic, phase, transcript, error, onBack, onStart, onStop, onRetry }: { topic: TeachTopic; phase: TeachPhase; transcript: string; error: string | null; onBack: () => void; onStart: () => void; onStop: () => void; onRetry: () => void }) {
  const recording = phase === 'recording';
  const busy = phase === 'transcribing' || phase === 'grading';
  return <div><button type="button" onClick={onBack} className="mb-4 inline-flex items-center gap-2 rounded-lg px-2 py-2 text-sm font-bold text-slate-500 hover:bg-white"><ArrowLeft size={17} /> Choose another topic</button><div className="rounded-2xl border border-brand-primary-tint bg-gradient-to-br from-orange-50 via-white to-brand-primary-bg p-4 sm:p-6"><p className="text-center text-xs font-bold uppercase tracking-[0.16em] text-brand-primary">Your topic</p><h2 className="mt-2 text-center text-2xl font-black tracking-tight text-slate-800">{topic.title}</h2><div className="relative mt-5 flex min-h-44 items-center justify-between gap-4 overflow-hidden"><FoxMascot /><Dartboard /></div><div className="mt-4 text-center"><button type="button" onClick={recording ? onStop : onStart} disabled={busy} aria-label={recording ? 'Stop recording' : 'Start explaining'} aria-pressed={recording} className={`mx-auto flex h-20 w-20 items-center justify-center rounded-full border-8 border-orange-100 text-white shadow-lg transition hover:scale-105 disabled:cursor-wait disabled:opacity-70 ${recording ? 'bg-red-500' : 'bg-brand-primary'}`}>{busy ? <LoaderCircle className="animate-spin" size={30} /> : recording ? <Square size={27} fill="currentColor" /> : <Mic size={30} />}</button><p className="mt-3 text-sm font-bold text-slate-600">{recording ? 'Tap to stop explaining' : busy ? (phase === 'grading' ? 'Grading your explanation…' : 'Listening back…') : 'Tap to start explaining'}</p></div>{recording && <div className="mx-auto mt-4 flex max-w-xs items-center justify-center gap-1" aria-label="Recording in progress">{Array.from({ length: 18 }, (_, index) => <span key={index} className="h-5 w-1 animate-pulse rounded-full bg-brand-primary" style={{ animationDelay: `${index * 45}ms`, transform: `scaleY(${0.4 + (index % 5) / 5})` }} />)}</div>}{transcript && <details className="mt-5 rounded-xl border border-slate-200 bg-white p-3 text-left"><summary className="cursor-pointer text-sm font-bold text-slate-700">What you said</summary><p className="mt-2 text-sm leading-6 text-slate-600" aria-live="polite">{transcript}</p></details>}</div>{error && <div className="mt-4 rounded-xl border border-red-200 bg-red-50 p-4 text-sm font-semibold text-red-700">{error}<button type="button" onClick={onRetry} className="ml-3 underline">Try again</button></div>}</div>;
}
