'use client';

import { ImagePlus, Send, X } from 'lucide-react';
import Image from 'next/image';
import { ChangeEvent, FormEvent, useState } from 'react';
import type { CommunityPost } from './types';

export default function PostComposer({ onClose, onPublish }: { onClose: () => void; onPublish: (post: CommunityPost) => void }) {
  const [title, setTitle] = useState(''); const [body, setBody] = useState(''); const [topic, setTopic] = useState('Computer Science'); const [imageUrl, setImageUrl] = useState<string>();
  const chooseImage = (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (file) setImageUrl(URL.createObjectURL(file)); };
  const submit = (event: FormEvent) => { event.preventDefault(); if (!title.trim() || !body.trim()) return; onPublish({ id: `post-${Date.now()}`, author: { name: 'You', handle: 'yourprofile', initials: 'YO', role: 'Student' }, title: title.trim(), body: body.trim(), topic, createdAt: 'Just now', likes: 0, liked: false, imageUrl, comments: [] }); };
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 px-4 py-6 backdrop-blur-sm"><form onSubmit={submit} className="max-h-full w-full max-w-2xl overflow-y-auto rounded-2xl bg-white p-5 shadow-2xl md:p-7"><div className="flex items-start justify-between"><div><h2 className="text-xl font-extrabold text-slate-800">Share with the community</h2><p className="mt-1 text-sm text-slate-500">Ask a question, share a solution, or post your study method.</p></div><button type="button" aria-label="Close composer" onClick={onClose} className="rounded-lg p-1 text-slate-400 hover:bg-slate-100"><X size={21} /></button></div><div className="mt-6 space-y-4"><input required value={title} onChange={(event) => setTitle(event.target.value)} maxLength={140} placeholder="Write a clear title" className="w-full rounded-xl border border-slate-200 px-4 py-3 text-sm font-semibold text-slate-800 outline-none transition focus:border-violet-400 focus:ring-4 focus:ring-violet-50" /><textarea required value={body} onChange={(event) => setBody(event.target.value)} maxLength={2000} rows={6} placeholder="Add context, your working, or the question you need help with..." className="w-full resize-none rounded-xl border border-slate-200 px-4 py-3 text-sm leading-6 text-slate-700 outline-none transition focus:border-violet-400 focus:ring-4 focus:ring-violet-50" /><div className="flex flex-wrap items-center justify-between gap-3"><select value={topic} onChange={(event) => setTopic(event.target.value)} className="rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm font-semibold text-slate-700 outline-none"><option>Computer Science</option><option>Mathematics</option><option>Physics</option><option>Study Skills</option></select><label className="inline-flex cursor-pointer items-center gap-2 rounded-xl border border-slate-200 px-3 py-2 text-sm font-bold text-slate-600 transition hover:bg-slate-50"><ImagePlus size={18} />Add photo<input className="hidden" type="file" accept="image/*" onChange={chooseImage} /></label></div>{imageUrl && <Image src={imageUrl} alt="Selected upload preview" width={720} height={208} unoptimized className="max-h-52 w-full rounded-xl object-cover" />}</div><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={onClose} className="rounded-xl px-4 py-3 text-sm font-bold text-slate-500 hover:bg-slate-100">Cancel</button><button type="submit" className="inline-flex items-center gap-2 rounded-xl bg-violet-600 px-5 py-3 text-sm font-bold text-white transition hover:bg-violet-700 disabled:opacity-50" disabled={!title.trim() || !body.trim()}><Send size={17} />Publish post</button></div></form></div>;
}
