'use client';

import { ImagePlus, LoaderCircle, Send, X } from 'lucide-react';
import Image from 'next/image';
import { ChangeEvent, FormEvent, useState } from 'react';
import { uploadCommunityImage } from '@/lib/community-api';

export default function PostComposer({ onClose, onPublish }: { onClose: () => void; onPublish: (post: { title: string; body: string; topic: string; image_url: string | null }) => Promise<void> }) {
  const [title, setTitle] = useState(''); const [body, setBody] = useState(''); const [topic, setTopic] = useState('Computer Science'); const [imageUrl, setImageUrl] = useState<string | null>(null); const [preview, setPreview] = useState<string>(); const [uploading, setUploading] = useState(false); const [error, setError] = useState<string | null>(null);
  const chooseImage = async (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; setError(null); setPreview(URL.createObjectURL(file)); setUploading(true); try { setImageUrl(await uploadCommunityImage(file)); } catch { setError('Image upload is unavailable right now.'); setPreview(undefined); } finally { setUploading(false); } };
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!title.trim() || !body.trim() || uploading) return; try { await onPublish({ title: title.trim(), body: body.trim(), topic, image_url: imageUrl }); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Could not publish your post.'); } };
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 px-4 py-6 backdrop-blur-sm"><form onSubmit={(event) => void submit(event)} className="max-h-full w-full max-w-2xl overflow-y-auto rounded-2xl bg-white p-5 shadow-2xl md:p-7"><div className="flex items-start justify-between"><div><h2 className="text-xl font-extrabold text-slate-800">Share with the community</h2><p className="mt-1 text-sm text-slate-500">Ask a question, share a solution, or post your study method.</p></div><button type="button" aria-label="Close composer" onClick={onClose} className="rounded-lg p-1 text-slate-400 hover:bg-slate-100"><X size={21} /></button></div><div className="mt-6 space-y-4"><input required value={title} onChange={(event) => setTitle(event.target.value)} maxLength={140} placeholder="Write a clear title" className="w-full rounded-xl border border-slate-200 px-4 py-3 text-sm font-semibold text-slate-800 outline-none" /><textarea required value={body} onChange={(event) => setBody(event.target.value)} maxLength={2000} rows={6} placeholder="Add context, your working, or the question you need help with..." className="w-full resize-none rounded-xl border border-slate-200 p-4 text-sm leading-6 text-slate-700 outline-none" /><div className="flex flex-wrap items-center justify-between gap-3"><select value={topic} onChange={(event) => setTopic(event.target.value)} className="rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm font-semibold text-slate-700"><option>Computer Science</option><option>Mathematics</option><option>Physics</option><option>Study Skills</option></select><label className="inline-flex cursor-pointer items-center gap-2 rounded-xl border border-slate-200 px-3 py-2 text-sm font-bold text-slate-600"><ImagePlus size={18} />{uploading ? 'Uploading…' : 'Add photo'}<input className="hidden" type="file" accept="image/jpeg,image/png,image/webp" onChange={(event) => void chooseImage(event)} /></label></div>{preview && <Image src={preview} alt="Selected upload preview" width={720} height={208} unoptimized className="max-h-52 w-full rounded-xl object-cover" />}{error && <p className="text-sm font-semibold text-red-600">{error}</p>}</div><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={onClose} className="rounded-xl px-4 py-3 text-sm font-bold text-slate-500">Cancel</button><button type="submit" disabled={!title.trim() || !body.trim() || uploading} className="inline-flex items-center gap-2 rounded-xl bg-brand-primary px-5 py-3 text-sm font-bold text-white disabled:opacity-50">{uploading && <LoaderCircle size={17} className="animate-spin" />}<Send size={17} />Publish post</button></div></form></div>;
}
