'use client';

import { Flag, LoaderCircle, X } from 'lucide-react';
import { useState } from 'react';
import { ApiError } from '@/lib/api';
import { reportCommunityContent } from '@/lib/community-api';

const reasons = [{ label: 'False or misleading information', value: 'Misleading information' }, { label: 'Harassment or bullying', value: 'Harassment or bullying' }, { label: 'Threats or unsafe content', value: 'Unsafe content' }, { label: 'Spam or unrelated content', value: 'Spam' }];

export default function ReportDialog({ targetType, targetId, onClose }: { targetType: 'post' | 'comment'; targetId: string; onClose: () => void }) {
  const [selected, setSelected] = useState(reasons[0].value); const [submitted, setSubmitted] = useState(false); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null);
  const submit = async () => { setLoading(true); setError(null); try { await reportCommunityContent(targetType, targetId, selected); setSubmitted(true); } catch (caught) { if (caught instanceof ApiError && caught.status === 409) setSubmitted(true); else setError('Could not submit the report. Please try again.'); } finally { setLoading(false); } };
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 px-4 backdrop-blur-sm" role="dialog" aria-modal="true" aria-labelledby="report-title"><div className="w-full max-w-md rounded-2xl bg-white p-6 shadow-2xl"><div className="flex items-start justify-between gap-4"><div><div className="mb-3 flex h-10 w-10 items-center justify-center rounded-xl bg-red-50 text-red-600"><Flag size={19} /></div><h2 id="report-title" className="text-lg font-extrabold text-slate-800">Report content</h2><p className="mt-1 text-sm leading-6 text-slate-500">Your report is private and will be reviewed by the moderation team.</p></div><button aria-label="Close report dialog" onClick={onClose} className="rounded-lg p-1 text-slate-400"><X size={20} /></button></div>{submitted ? <div className="mt-6 rounded-xl bg-emerald-50 p-4 text-sm font-semibold text-emerald-700">Report submitted. Thank you for helping keep the community safe.</div> : <><div className="mt-6 space-y-2">{reasons.map((reason) => <label key={reason.value} className={`flex cursor-pointer items-center gap-3 rounded-xl border p-3 text-sm font-medium ${selected === reason.value ? 'border-brand-primary-light bg-brand-primary-bg text-brand-primary-dark' : 'border-slate-200 text-slate-600'}`}><input type="radio" name="reason" checked={selected === reason.value} onChange={() => setSelected(reason.value)} className="accent-brand-primary" />{reason.label}</label>)}</div>{error && <p className="mt-4 text-sm font-semibold text-red-600">{error}</p>}<button disabled={loading} onClick={() => void submit()} className="mt-6 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-red-600 px-4 py-3 text-sm font-bold text-white disabled:opacity-60">{loading && <LoaderCircle size={16} className="animate-spin" />}Submit report</button></>}</div></div>;
}
